# Date: 2024-11-28
# Author: Joohanhong <joohan.hong@kt.com>

name: Trivy CVE Version MGMT

on:
  push:
    branches:
      - main
  pull_request:

env:
  MOVER: '192.168.4.8'

jobs:
  trivy-cve_database_update:
    runs-on: [self-hosted,Linux,X64,fetcher01]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Trivy Vulnerability Reference File Update and Deploy
        run: |
          sudo rm -rf /home/fetcher01/cve_latest.txt
          sudo cp -rf cve_latest.txt /home/fetcher01/cve_latest.txt
          sudo chown fetcher01.fetcher01 /home/fetcher01/cve_latest.txt
          scp -P 22 /home/fetcher01/cve_latest.txt devops@${{ env.MOVER }}:./cve_latest.txt
          
      - name: GitHub Build Fail Sending Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: 'Trivy CVE Lists MGMT Git Build Failed!'
          fields: repo, messages, commit, author, action, eventName, ref, workflow, job, took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()

      - name: GitHub Build Success Sending Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: 'Trivy CVE Lists MGMT Git Build Successed.'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: success()
